import React, { useEffect, useState } from 'react';
import { CalendarClock, Loader2, Pause, Play, Trash2 } from 'lucide-react';
import { apiFetch } from '../lib/api';

interface Schedule { id: string; targetUrl: string; frequency: 'DAILY' | 'WEEKLY'; enabled: boolean; nextRunAt: string; }
export const SchedulesView: React.FC = () => {
  const [schedules, setSchedules] = useState<Schedule[]>([]); const [targetUrl, setTargetUrl] = useState(''); const [frequency, setFrequency] = useState<'DAILY' | 'WEEKLY'>('DAILY'); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [message, setMessage] = useState('');
  const load = async () => { setLoading(true); try { const response = await apiFetch('/api/schedules'); if (!response.ok) throw new Error('Unable to load schedules'); setSchedules((await response.json()).schedules || []); } catch (error: any) { setMessage(error.message); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const create = async (event: React.FormEvent) => { event.preventDefault(); setSaving(true); setMessage(''); try { const response = await apiFetch('/api/schedules', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ targetUrl, frequency }) }); if (!response.ok) throw new Error((await response.json()).error?.message || 'Unable to create schedule'); setTargetUrl(''); setMessage('Schedule created.'); await load(); } catch (error: any) { setMessage(error.message); } finally { setSaving(false); } };
  const update = async (schedule: Schedule, updates: Partial<Schedule>) => { try { const response = await apiFetch(`/api/schedules/${schedule.id}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(updates) }); if (!response.ok) throw new Error('Unable to update schedule'); await load(); } catch (error: any) { setMessage(error.message); } };
  const remove = async (schedule: Schedule) => { try { const response = await apiFetch(`/api/schedules/${schedule.id}`, { method: 'DELETE' }); if (!response.ok) throw new Error('Unable to delete schedule'); setSchedules(current => current.filter(item => item.id !== schedule.id)); } catch (error: any) { setMessage(error.message); } };
  return <div className="space-y-6 animate-fade-in"><div className="rounded-3xl border border-slate-800 bg-slate-900/80 p-6 md:p-8"><div className="flex items-center gap-3"><CalendarClock className="h-6 w-6 text-rose-400" /><div><h2 className="text-2xl font-bold text-white">Scheduled Scans</h2><p className="text-xs text-slate-400 mt-1">Keep recurring website audits in the existing background queue.</p></div></div><form onSubmit={create} className="mt-6 flex flex-col md:flex-row gap-3"><input value={targetUrl} onChange={event => setTargetUrl(event.target.value)} type="url" required placeholder="https://your-site.com" className="flex-1 rounded-xl border border-slate-700 bg-slate-950 px-4 py-3 text-sm text-white" /><select value={frequency} onChange={event => setFrequency(event.target.value as 'DAILY' | 'WEEKLY')} className="rounded-xl border border-slate-700 bg-slate-950 px-4 py-3 text-sm text-white"><option value="DAILY">Daily</option><option value="WEEKLY">Weekly</option></select><button disabled={saving} className="inline-flex items-center justify-center gap-2 rounded-xl bg-rose-600 px-5 py-3 text-sm font-bold text-white disabled:opacity-50">{saving && <Loader2 className="h-4 w-4 animate-spin" />}Create</button></form>{message && <p className="mt-3 text-xs text-amber-300">{message}</p>}</div><div className="space-y-3">{loading ? <div className="p-8 text-center text-sm text-slate-400">Loading schedules...</div> : schedules.length === 0 ? <div className="rounded-2xl border border-dashed border-slate-700 p-8 text-center text-sm text-slate-400">No scheduled scans yet.</div> : schedules.map(schedule => <div key={schedule.id} className="flex flex-col md:flex-row md:items-center justify-between gap-4 rounded-2xl border border-slate-800 bg-slate-900/70 p-4"><div><div className="font-mono text-sm text-white truncate max-w-xl">{schedule.targetUrl}</div><div className="mt-1 text-xs text-slate-400">{schedule.frequency} · next run {new Date(schedule.nextRunAt).toLocaleString()} · {schedule.enabled ? 'Active' : 'Paused'}</div></div><div className="flex items-center gap-2"><button title={schedule.enabled ? 'Pause' : 'Resume'} onClick={() => update(schedule, { enabled: !schedule.enabled })} className="rounded-lg border border-slate-700 p-2 text-slate-300 hover:text-white">{schedule.enabled ? <Pause className="h-4 w-4" /> : <Play className="h-4 w-4" />}</button><button title="Delete" onClick={() => remove(schedule)} className="rounded-lg border border-slate-700 p-2 text-rose-300 hover:text-rose-200"><Trash2 className="h-4 w-4" /></button></div></div>)}</div></div>;
};
