export interface FeatureRecord {
  id: string;
  name: string;
  category: 'SCANNER' | 'RADAR' | 'MONITORING' | 'AGENCY' | 'MONETIZATION' | 'SECURITY' | 'REPORTS' | 'UTILITY';
  component: string;
  routeOrTab: string;
  backendEndpoint?: string;
  status: 'ACTIVE' | 'CONNECTED' | 'PRODUCTION_READY';
  modeSupport: 'BOTH' | 'REAL_ONLY' | 'DEMO_ONLY';
  hasTests: boolean;
  description: string;
}

export const FEATURE_REGISTRY: FeatureRecord[] = [
  {
    id: 'LG-001',
    name: 'WhatsApp Routing & +9191 Bug Scanner',
    category: 'SCANNER',
    component: 'HeroScanner / FindingsDetailTabs',
    routeOrTab: 'scanner',
    backendEndpoint: 'POST /api/scan',
    status: 'PRODUCTION_READY',
    modeSupport: 'BOTH',
    hasTests: true,
    description: 'Detects duplicate +9191 country codes, leading 0-prefix bugs, and malformed wa.me parameters that crash mobile WhatsApp apps.',
  },
  {
    id: 'LG-002',
    name: 'Zero-Intent WhatsApp Message Optimizer',
    category: 'SCANNER',
    component: 'ZeroIntentChecker / FindingsDetailTabs',
    routeOrTab: 'zero-intent',
    backendEndpoint: 'POST /api/scan',
    status: 'PRODUCTION_READY',
    modeSupport: 'BOTH',
    hasTests: true,
    description: 'Checks if WhatsApp contact links carry high-converting pre-filled messages or open to a blank chat.',
  },
  {
    id: 'LG-003',
    name: 'Click-to-Call Dialer Health Probe',
    category: 'SCANNER',
    component: 'ChannelMatrix / FindingsDetailTabs',
    routeOrTab: 'scanner',
    backendEndpoint: 'POST /api/scan',
    status: 'PRODUCTION_READY',
    modeSupport: 'BOTH',
    hasTests: true,
    description: 'Validates tel: links for 10-digit Indian mobile and landline standards.',
  },
  {
    id: 'LG-004',
    name: 'Email & Mailto Syntax Validator',
    category: 'SCANNER',
    component: 'ChannelMatrix / FindingsDetailTabs',
    routeOrTab: 'scanner',
    backendEndpoint: 'POST /api/scan',
    status: 'PRODUCTION_READY',
    modeSupport: 'BOTH',
    hasTests: true,
    description: 'Checks mailto: protocol links for RFC-compliant formatting and non-empty destinations.',
  },
  {
    id: 'LG-005',
    name: 'Google Business Profile & Reviews Resolver',
    category: 'SCANNER',
    component: 'ChannelMatrix / FindingsDetailTabs',
    routeOrTab: 'scanner',
    backendEndpoint: 'POST /api/scan',
    status: 'PRODUCTION_READY',
    modeSupport: 'BOTH',
    hasTests: true,
    description: 'Checks Google Reviews and Maps shortlinks (g.page, maps.app.goo.gl) for valid destinations.',
  },
  {
    id: 'LG-006',
    name: 'AdShield Meta Pixel Inspector',
    category: 'SCANNER',
    component: 'FourPillarsOverview / FindingsDetailTabs',
    routeOrTab: 'scanner',
    backendEndpoint: 'POST /api/scan',
    status: 'PRODUCTION_READY',
    modeSupport: 'BOTH',
    hasTests: true,
    description: 'Detects Meta Pixel (fbq) initialization, duplicate trackers, and missing attribution tags on ad landing pages.',
  },
  {
    id: 'LG-007',
    name: 'Google Analytics GA4 & GTM Inspector',
    category: 'SCANNER',
    component: 'FourPillarsOverview / FindingsDetailTabs',
    routeOrTab: 'scanner',
    backendEndpoint: 'POST /api/scan',
    status: 'PRODUCTION_READY',
    modeSupport: 'BOTH',
    hasTests: true,
    description: 'Detects GA4 measurement IDs (G-XXXXX) and Google Tag Manager (GTM-XXXXX) containers.',
  },
  {
    id: 'LG-008',
    name: 'SEO De-Indexation & Robots Penalty Shield',
    category: 'SCANNER',
    component: 'FourPillarsOverview / FindingsDetailTabs',
    routeOrTab: 'scanner',
    backendEndpoint: 'POST /api/scan',
    status: 'PRODUCTION_READY',
    modeSupport: 'BOTH',
    hasTests: true,
    description: 'Catches accidental <meta name="robots" content="noindex">, missing SSL/HTTPS, and broken canonical links.',
  },
  {
    id: 'LG-009',
    name: 'Cyber & Hack Injection Heuristic Engine',
    category: 'SECURITY',
    component: 'FourPillarsOverview / FindingsDetailTabs',
    routeOrTab: 'scanner',
    backendEndpoint: 'POST /api/scan',
    status: 'PRODUCTION_READY',
    modeSupport: 'BOTH',
    hasTests: true,
    description: 'Scans for unauthorized spam/gambling keyword injections, obfuscated eval(atob()) script loaders, and hidden 0px iframes.',
  },
  {
    id: 'LG-010',
    name: 'E-Commerce Cart Death Monitor',
    category: 'SCANNER',
    component: 'CartDeathMonitor / FindingsDetailTabs',
    routeOrTab: 'cart-death',
    backendEndpoint: 'POST /api/scan',
    status: 'PRODUCTION_READY',
    modeSupport: 'BOTH',
    hasTests: true,
    description: 'Detects broken or unrouted Add to Cart and Checkout buttons linking to # or dead handlers.',
  },
  {
    id: 'LG-011',
    name: 'SSRF & RFC1918 Defense Shield',
    category: 'SECURITY',
    component: 'Server Middleware / ssrfGuard',
    routeOrTab: 'backend',
    backendEndpoint: 'POST /api/scan',
    status: 'PRODUCTION_READY',
    modeSupport: 'REAL_ONLY',
    hasTests: true,
    description: 'DNS pre-resolution and IP validation blocking loopback, link-local, cloud metadata, and private network addresses.',
  },
  {
    id: 'LG-012',
    name: 'Transparent Revenue Impact & Loss Estimator',
    category: 'UTILITY',
    component: 'RevenueScenarioCalculator / ScoreDashboard',
    routeOrTab: 'scanner',
    backendEndpoint: 'POST /api/scan',
    status: 'PRODUCTION_READY',
    modeSupport: 'BOTH',
    hasTests: true,
    description: 'Formula-based potential loss calculation with customizable visitor, conversion, and average lead value parameters.',
  },
  {
    id: 'LG-013',
    name: 'Interactive Funnel Leak Simulator',
    category: 'UTILITY',
    component: 'FunnelLeakSimulator',
    routeOrTab: 'funnel',
    backendEndpoint: 'POST /api/scan',
    status: 'PRODUCTION_READY',
    modeSupport: 'BOTH',
    hasTests: true,
    description: 'Live interactive sandbox visualizing how ad spend drops off step-by-step through broken conversion channels.',
  },
  {
    id: 'LG-014',
    name: 'Public Shareable Forensic Audit Reports',
    category: 'REPORTS',
    component: 'PublicReportView / ShareableReportModal',
    routeOrTab: 'report/:scanId',
    backendEndpoint: 'GET /api/scan/:id',
    status: 'PRODUCTION_READY',
    modeSupport: 'BOTH',
    hasTests: true,
    description: 'Client-accessible standalone URL report with health scores, evidence logs, PDF export, and express fix CTAs.',
  },
  {
    id: 'LG-015',
    name: 'Client-Side & Server PDF Audit Report Generator',
    category: 'REPORTS',
    component: 'ScoreDashboard / PublicReportView / pdfGenerator',
    routeOrTab: 'scanner',
    backendEndpoint: 'GET /api/scan/:id/export',
    status: 'PRODUCTION_READY',
    modeSupport: 'BOTH',
    hasTests: true,
    description: 'Generates branded executive PDF audit reports with 4-pillar scores, detected code leaks, and remediation advice.',
  },
  {
    id: 'LG-016',
    name: '24/7 Watchdog Heartbeat Monitoring Radar',
    category: 'MONITORING',
    component: 'WatchdogConsole / WatchdogModal',
    routeOrTab: 'watchdog',
    backendEndpoint: 'POST /api/watchdog/subscribe, GET /api/watchdog/list',
    status: 'PRODUCTION_READY',
    modeSupport: 'BOTH',
    hasTests: true,
    description: 'Scheduled automated probe verifying WhatsApp links, call buttons, and tracking pixels with instant downtime alerts.',
  },
  {
    id: 'LG-017',
    name: 'HMAC-SHA256 Webhook & Incident Dispatcher',
    category: 'MONITORING',
    component: 'WebhooksManager',
    routeOrTab: 'watchdog',
    backendEndpoint: 'POST /api/webhooks/register, POST /api/webhooks/test',
    status: 'PRODUCTION_READY',
    modeSupport: 'BOTH',
    hasTests: true,
    description: 'Cryptographically signed webhook notifications for Slack, Discord, Zapier, and custom agency endpoints.',
  },
  {
    id: 'LG-018',
    name: 'Competitor Sabotage Radar',
    category: 'RADAR',
    component: 'CompetitorSabotageRadar',
    routeOrTab: 'sabotage-radar',
    backendEndpoint: 'POST /api/competitor-sabotage',
    status: 'PRODUCTION_READY',
    modeSupport: 'BOTH',
    hasTests: true,
    description: 'Multi-URL comparative crawler discovering competitor conversion leaks to exploit via Google Search and Meta Ads.',
  },
  {
    id: 'LG-019',
    name: 'Hunter Mode — 116 Pre-Audited SME Leads Vault',
    category: 'AGENCY',
    component: 'HunterMode',
    routeOrTab: 'hunter',
    backendEndpoint: 'POST /api/scan-batch',
    status: 'PRODUCTION_READY',
    modeSupport: 'BOTH',
    hasTests: true,
    description: 'Curated database of Indian SME websites with confirmed revenue leaks, 1-click WhatsApp pitch generator, and CSV export.',
  },
  {
    id: 'LG-020',
    name: 'Agency Tools Hub & Batch Prospect Scanner',
    category: 'AGENCY',
    component: 'AgencyToolsHub / BatchProspectScanner',
    routeOrTab: 'agency',
    backendEndpoint: 'POST /api/scan-batch',
    status: 'PRODUCTION_READY',
    modeSupport: 'BOTH',
    hasTests: true,
    description: 'Bulk audits up to 500 domain URLs simultaneously, generating forensic pitch decks and WhatsApp outreach copy.',
  },
  {
    id: 'LG-021',
    name: 'AI-Powered Cold Pitch Generator (Hinglish & English)',
    category: 'AGENCY',
    component: 'AgencyPitchSuite',
    routeOrTab: 'agency',
    backendEndpoint: 'POST /api/ai/pitch-generator',
    status: 'PRODUCTION_READY',
    modeSupport: 'BOTH',
    hasTests: true,
    description: 'Leverages Gemini API to generate personalized client outreach messages in professional Hindi/Hinglish or English.',
  },
  {
    id: 'LG-022',
    name: 'AutoFix Script Studio & 1-Click Code Injectors',
    category: 'UTILITY',
    component: 'AutoFixScriptStudio',
    routeOrTab: 'agency',
    backendEndpoint: 'GET /api/scan/:id',
    status: 'PRODUCTION_READY',
    modeSupport: 'BOTH',
    hasTests: true,
    description: 'Zero-touch JavaScript snippets for WordPress, Shopify, Next.js, and Webflow to auto-correct +9191 bugs on the fly.',
  },
  {
    id: 'LG-023',
    name: 'WhatsApp Floating Lead Widget Generator',
    category: 'UTILITY',
    component: 'WidgetGenerator',
    routeOrTab: 'agency',
    backendEndpoint: 'POST /api/scan',
    status: 'PRODUCTION_READY',
    modeSupport: 'BOTH',
    hasTests: true,
    description: 'Embeddable high-converting floating chat badge with pre-filled greeting message and avatar customizer.',
  },
  {
    id: 'LG-024',
    name: 'Mobile Sandbox Link Debugger',
    category: 'UTILITY',
    component: 'LinkDebuggerSandbox',
    routeOrTab: 'agency',
    backendEndpoint: 'POST /api/scan',
    status: 'PRODUCTION_READY',
    modeSupport: 'BOTH',
    hasTests: true,
    description: 'Interactive sandbox testing how WhatsApp and tel: links behave across iOS, Android, and Desktop WhatsApp Web.',
  },
  {
    id: 'LG-025',
    name: '3-Tier Monetization Stack & UPI Checkout',
    category: 'MONETIZATION',
    component: 'MonetizationVault / FreeFixAndLockedPaywall',
    routeOrTab: 'pricing',
    backendEndpoint: 'POST /api/monetization/order',
    status: 'PRODUCTION_READY',
    modeSupport: 'BOTH',
    hasTests: true,
    description: 'One-time audit fixes (₹2,999-₹6,999), SaaS subscriptions (₹99-₹999/mo), and white-label agency licenses with UPI checkout.',
  },
  {
    id: 'LG-026',
    name: 'Express 48h DFY Fix Service Booking',
    category: 'MONETIZATION',
    component: 'ExpressFixModal',
    routeOrTab: 'scanner',
    backendEndpoint: 'POST /api/monetization/order',
    status: 'PRODUCTION_READY',
    modeSupport: 'BOTH',
    hasTests: true,
    description: 'Direct DFY emergency fix request with Indian engineer assignment and WhatsApp update delivery.',
  },
  {
    id: 'LG-027',
    name: 'Live Real-Time Global Scan Counters',
    category: 'UTILITY',
    component: 'ScanCounterStats',
    routeOrTab: 'scanner',
    backendEndpoint: 'GET /api/scan-stats, POST /api/scan-stats/increment-fix',
    status: 'PRODUCTION_READY',
    modeSupport: 'BOTH',
    hasTests: true,
    description: 'Real-time counters tracking total scanned websites, problems diagnosed, and revenue funnels patched.',
  },
  {
    id: 'LG-028',
    name: 'Founder Direct Contact & Support Modal',
    category: 'UTILITY',
    component: 'ContactUsModal',
    routeOrTab: 'modal',
    backendEndpoint: 'N/A',
    status: 'PRODUCTION_READY',
    modeSupport: 'BOTH',
    hasTests: true,
    description: 'Direct contact modal with Founder phone (+91 83070 70605) and email (mohitsikarwar123@gmail.com).',
  },
];
