export interface FeatureRecord {
  id: string;
  name: string;
  category: 'SCANNER' | 'RADAR' | 'MONITORING' | 'AGENCY' | 'MONETIZATION' | 'SECURITY' | 'REPORTS' | 'UTILITY';
  component: string;
  routeOrTab: string;
  backendEndpoint?: string;
  status: 'ACTIVE' | 'CONNECTED' | 'PRODUCTION_READY';
  modeSupport: 'BOTH' | 'REAL_ONLY' | 'DEMO_ONLY';
  storage: 'FIRESTORE' | 'LOCAL' | 'HYBRID';
  mode: 'LIVE' | 'DEMO' | 'BOTH';
  production: 'READY' | 'PARTIAL' | 'BLOCKED';
  hasTests: boolean;
  description: string;
}

export const FEATURE_REGISTRY: FeatureRecord[] = [
  {
    id: 'LG-001',
    name: 'WhatsApp Routing & +9191 Bug Scanner',
    category: 'SCANNER',
    component: 'HeroScanner / FindingsDetailTabs',
    routeOrTab: 'scanner',
    backendEndpoint: 'POST /api/scan',
    status: 'PRODUCTION_READY',
    modeSupport: 'BOTH',
    storage: 'FIRESTORE',
    mode: 'BOTH',
    production: 'READY',
    hasTests: true,
    description: 'Detects duplicate +9191 country codes, leading 0-prefix bugs, and malformed wa.me parameters that crash mobile WhatsApp apps.',
  },
  {
    id: 'LG-002',
    name: 'Zero-Intent WhatsApp Message Optimizer',
    category: 'SCANNER',
    component: 'ZeroIntentChecker / FindingsDetailTabs',
    routeOrTab: 'zero-intent',
    backendEndpoint: 'POST /api/scan',
    status: 'PRODUCTION_READY',
    modeSupport: 'BOTH',
    storage: 'FIRESTORE',
    mode: 'BOTH',
    production: 'READY',
    hasTests: true,
    description: 'Checks if WhatsApp contact links carry high-converting pre-filled messages or open to a blank chat.',
  },
  {
    id: 'LG-003',
    name: 'Click-to-Call Dialer Health Probe',
    category: 'SCANNER',
    component: 'ChannelMatrix / FindingsDetailTabs',
    routeOrTab: 'scanner',
    backendEndpoint: 'POST /api/scan',
    status: 'PRODUCTION_READY',
    modeSupport: 'BOTH',
    storage: 'FIRESTORE',
    mode: 'BOTH',
    production: 'READY',
    hasTests: true,
    description: 'Validates tel: links for 10-digit Indian mobile and landline standards.',
  },
  {
    id: 'LG-004',
    name: 'Email & Mailto Syntax Validator',
    category: 'SCANNER',
    component: 'ChannelMatrix / FindingsDetailTabs',
    routeOrTab: 'scanner',
    backendEndpoint: 'POST /api/scan',
    status: 'PRODUCTION_READY',
    modeSupport: 'BOTH',
    storage: 'FIRESTORE',
    mode: 'BOTH',
    production: 'READY',
    hasTests: true,
    description: 'Checks mailto: protocol links for RFC-compliant formatting and non-empty destinations.',
  },
  {
    id: 'LG-005',
    name: 'Google Business Profile & Reviews Resolver',
    category: 'SCANNER',
    component: 'ChannelMatrix / FindingsDetailTabs',
    routeOrTab: 'scanner',
    backendEndpoint: 'POST /api/scan',
    status: 'PRODUCTION_READY',
    modeSupport: 'BOTH',
    storage: 'FIRESTORE',
    mode: 'BOTH',
    production: 'READY',
    hasTests: true,
    description: 'Checks Google Reviews and Maps shortlinks (g.page, maps.app.goo.gl) for valid destinations.',
  },
  {
    id: 'LG-006',
    name: 'AdShield Meta Pixel Inspector',
    category: 'SCANNER',
    component: 'FourPillarsOverview / FindingsDetailTabs',
    routeOrTab: 'scanner',
    backendEndpoint: 'POST /api/scan',
    status: 'PRODUCTION_READY',
    modeSupport: 'BOTH',
    storage: 'FIRESTORE',
    mode: 'BOTH',
    production: 'READY',
    hasTests: true,
    description: 'Detects Meta Pixel (fbq) initialization, duplicate trackers, and missing attribution tags on ad landing pages.',
  },
  {
    id: 'LG-007',
    name: 'Google Analytics GA4 & GTM Inspector',
    category: 'SCANNER',
    component: 'FourPillarsOverview / FindingsDetailTabs',
    routeOrTab: 'scanner',
    backendEndpoint: 'POST /api/scan',
    status: 'PRODUCTION_READY',
    modeSupport: 'BOTH',
    storage: 'FIRESTORE',
    mode: 'BOTH',
    production: 'READY',
    hasTests: true,
    description: 'Detects GA4 measurement IDs (G-XXXXX) and Google Tag Manager (GTM-XXXXX) containers.',
  },
  {
    id: 'LG-008',
    name: 'UTM Tracking & Ad Attribution Auditor',
    category: 'SCANNER',
    component: 'FourPillarsOverview / FindingsDetailTabs',
    routeOrTab: 'scanner',
    backendEndpoint: 'POST /api/scan',
    status: 'PRODUCTION_READY',
    modeSupport: 'BOTH',
    storage: 'FIRESTORE',
    mode: 'BOTH',
    production: 'READY',
    hasTests: true,
    description: 'Verifies landing page preservation of UTM campaign parameters across CTA destination links.',
  },
  {
    id: 'LG-009',
    name: 'Ad Spend Waste Multiplier Calculator',
    category: 'SCANNER',
    component: 'AdWasteCalculator / RevenueImpactHero',
    routeOrTab: 'scanner',
    backendEndpoint: 'POST /api/scan',
    status: 'PRODUCTION_READY',
    modeSupport: 'BOTH',
    storage: 'FIRESTORE',
    mode: 'BOTH',
    production: 'READY',
    hasTests: true,
    description: 'Calculates monthly and annual financial loss in ₹INR based on monthly ad budget, CPC, and conversion leak rates.',
  },
  {
    id: 'LG-010',
    name: 'SEO Shield Noindex & Meta Robots Detector',
    category: 'SCANNER',
    component: 'FourPillarsOverview / FindingsDetailTabs',
    routeOrTab: 'scanner',
    backendEndpoint: 'POST /api/scan',
    status: 'PRODUCTION_READY',
    modeSupport: 'BOTH',
    storage: 'FIRESTORE',
    mode: 'BOTH',
    production: 'READY',
    hasTests: true,
    description: 'Flags accidental <meta name="robots" content="noindex"> directives that completely wipe sites from Google search.',
  },
  {
    id: 'LG-011',
    name: 'Canonical Tag & URL Structure Validator',
    category: 'SCANNER',
    component: 'FourPillarsOverview / FindingsDetailTabs',
    routeOrTab: 'scanner',
    backendEndpoint: 'POST /api/scan',
    status: 'PRODUCTION_READY',
    modeSupport: 'BOTH',
    storage: 'FIRESTORE',
    mode: 'BOTH',
    production: 'READY',
    hasTests: true,
    description: 'Ensures canonical link tags are present, non-broken, and point to self or designated master URLs.',
  },
  {
    id: 'LG-012',
    name: 'OpenGraph & Twitter Card Social Previewer',
    category: 'SCANNER',
    component: 'ChannelMatrix / FindingsDetailTabs',
    routeOrTab: 'scanner',
    backendEndpoint: 'POST /api/scan',
    status: 'PRODUCTION_READY',
    modeSupport: 'BOTH',
    storage: 'FIRESTORE',
    mode: 'BOTH',
    production: 'READY',
    hasTests: true,
    description: 'Validates og:title, og:image, og:description for high-CTR link previews on WhatsApp and social sharing.',
  },
  {
    id: 'LG-013',
    name: 'CyberShield SSL/TLS Expiry & Mixed Content Probe',
    category: 'SECURITY',
    component: 'FourPillarsOverview / FindingsDetailTabs',
    routeOrTab: 'scanner',
    backendEndpoint: 'POST /api/scan',
    status: 'PRODUCTION_READY',
    modeSupport: 'BOTH',
    storage: 'FIRESTORE',
    mode: 'BOTH',
    production: 'READY',
    hasTests: true,
    description: 'Checks HTTPS protocol enforcement, SSL validity, and flags insecure HTTP mixed content resources.',
  },
  {
    id: 'LG-014',
    name: 'Security Headers & CSP/HSTS Policy Scanner',
    category: 'SECURITY',
    component: 'FourPillarsOverview / FindingsDetailTabs',
    routeOrTab: 'scanner',
    backendEndpoint: 'POST /api/scan',
    status: 'PRODUCTION_READY',
    modeSupport: 'BOTH',
    storage: 'FIRESTORE',
    mode: 'BOTH',
    production: 'READY',
    hasTests: true,
    description: 'Audits HSTS, X-Frame-Options, X-Content-Type-Options, and Content-Security-Policy headers.',
  },
  {
    id: 'LG-015',
    name: 'Server-Side SSRF & Network Defense Engine',
    category: 'SECURITY',
    component: 'Server SSRF Guard Middleware',
    routeOrTab: 'scanner',
    backendEndpoint: 'POST /api/scan, POST /api/watchdog/subscribe, POST /api/webhooks/*',
    status: 'PRODUCTION_READY',
    modeSupport: 'REAL_ONLY',
    storage: 'FIRESTORE',
    mode: 'LIVE',
    production: 'READY',
    hasTests: true,
    description: 'Blocks private IP subnets (RFC 1918), localhost, loopback, link-local, and cloud metadata access.',
  },
  {
    id: 'LG-016',
    name: 'Transparent Revenue Impact & Loss Model',
    category: 'SCANNER',
    component: 'RevenueImpactHero / AdWasteCalculator',
    routeOrTab: 'scanner',
    backendEndpoint: 'POST /api/scan',
    status: 'PRODUCTION_READY',
    modeSupport: 'BOTH',
    storage: 'FIRESTORE',
    mode: 'BOTH',
    production: 'READY',
    hasTests: true,
    description: 'Multi-factor financial loss calculator with formula transparency badge and slider adjustments.',
  },
  {
    id: 'LG-017',
    name: '24/7 Watchdog Heartbeat Monitor & Alerts',
    category: 'MONITORING',
    component: 'WatchdogRadarTab / WatchdogLeadMagnetModal',
    routeOrTab: 'watchdog',
    backendEndpoint: 'POST /api/watchdog/subscribe, GET /api/watchdog/list',
    status: 'PRODUCTION_READY',
    modeSupport: 'BOTH',
    storage: 'FIRESTORE',
    mode: 'BOTH',
    production: 'READY',
    hasTests: true,
    description: 'Real-time background scheduler checking link health, pixel drops, and sending Telegram/WhatsApp alerts.',
  },
  {
    id: 'LG-018',
    name: 'Incident Webhooks & HMAC-SHA256 Signatures',
    category: 'MONITORING',
    component: 'WebhooksSettingsTab',
    routeOrTab: 'webhooks',
    backendEndpoint: 'POST /api/webhooks/register, GET /api/webhooks/list, POST /api/webhooks/test',
    status: 'PRODUCTION_READY',
    modeSupport: 'BOTH',
    storage: 'FIRESTORE',
    mode: 'BOTH',
    production: 'READY',
    hasTests: true,
    description: 'Cryptographically signed webhook dispatcher delivering real-time incident payloads to Slack, Zapier, Make.',
  },
  {
    id: 'LG-019',
    name: 'Competitor Sabotage Radar & Growth Hunter',
    category: 'RADAR',
    component: 'CompetitorSabotageTab',
    routeOrTab: 'sabotage',
    backendEndpoint: 'POST /api/competitor-sabotage',
    status: 'PRODUCTION_READY',
    modeSupport: 'BOTH',
    storage: 'FIRESTORE',
    mode: 'BOTH',
    production: 'READY',
    hasTests: true,
    description: 'Multi-site comparative scanner identifying competitor ad leaks to run targeted conquest ad campaigns.',
  },
  {
    id: 'LG-020',
    name: 'Agency 500-Site Lead Hunter & Batch Scanner',
    category: 'AGENCY',
    component: 'LeadHunterBatchTab',
    routeOrTab: 'lead-hunter',
    backendEndpoint: 'POST /api/scan-batch',
    status: 'PRODUCTION_READY',
    modeSupport: 'BOTH',
    storage: 'FIRESTORE',
    mode: 'BOTH',
    production: 'READY',
    hasTests: true,
    description: 'High-throughput batch auditor scanning up to 500 prospect URLs, calculating total pipeline leakage, and generating outreach pitches.',
  },
  {
    id: 'LG-021',
    name: 'Hinglish AI Pitch & Cold WhatsApp Generator',
    category: 'AGENCY',
    component: 'AiPitchGeneratorTab',
    routeOrTab: 'pitch-generator',
    backendEndpoint: 'POST /api/ai/pitch-generator',
    status: 'PRODUCTION_READY',
    modeSupport: 'BOTH',
    storage: 'FIRESTORE',
    mode: 'BOTH',
    production: 'READY',
    hasTests: true,
    description: 'Generates high-converting cold pitches in Hinglish and English personalized to detected technical audit flaws.',
  },
  {
    id: 'LG-022',
    name: 'Public Shareable Audit Reports & Client Links',
    category: 'REPORTS',
    component: 'ShareReportModal / PublicReportView',
    routeOrTab: 'report/:id',
    backendEndpoint: 'GET /api/scan/:id, GET /api/report/:token',
    status: 'PRODUCTION_READY',
    modeSupport: 'BOTH',
    storage: 'FIRESTORE',
    mode: 'BOTH',
    production: 'READY',
    hasTests: true,
    description: 'Secure, client-safe public audit reports accessed via cryptographic tokens without exposing private account data.',
  },
  {
    id: 'LG-023',
    name: 'White-Label Agency Client PDF Report Generator',
    category: 'REPORTS',
    component: 'PdfExportButton / WhiteLabelPdfModal',
    routeOrTab: 'scanner',
    backendEndpoint: 'Client-side jsPDF with Agency Custom Branding',
    status: 'PRODUCTION_READY',
    modeSupport: 'BOTH',
    storage: 'FIRESTORE',
    mode: 'BOTH',
    production: 'READY',
    hasTests: true,
    description: 'Customizable PDF audit generator with agency logo, custom color theme, pricing proposals, and client presentation mode.',
  },
  {
    id: 'LG-024',
    name: 'Device-Specific Link Simulator (iOS / Android / Web)',
    category: 'SCANNER',
    component: 'DeviceSimulatorModal',
    routeOrTab: 'scanner',
    backendEndpoint: 'Client-side simulation engine',
    status: 'PRODUCTION_READY',
    modeSupport: 'BOTH',
    storage: 'FIRESTORE',
    mode: 'BOTH',
    production: 'READY',
    hasTests: true,
    description: 'Interactive sandbox testing how WhatsApp and tel: links behave across iOS, Android, and Desktop WhatsApp Web.',
  },
  {
    id: 'LG-025',
    name: '3-Tier Monetization Stack & UPI Checkout',
    category: 'MONETIZATION',
    component: 'MonetizationVault / FreeFixAndLockedPaywall',
    routeOrTab: 'pricing',
    backendEndpoint: 'POST /api/monetization/order, POST /api/monetization/orders/verify',
    status: 'PRODUCTION_READY',
    modeSupport: 'BOTH',
    storage: 'FIRESTORE',
    mode: 'BOTH',
    production: 'READY',
    hasTests: true,
    description: 'One-time audit fixes (₹2,999-₹6,999), SaaS subscriptions (₹99-₹999/mo), and white-label agency licenses with UPI checkout.',
  },
  {
    id: 'LG-026',
    name: 'Express 48h DFY Fix Service Booking',
    category: 'MONETIZATION',
    component: 'ExpressFixModal',
    routeOrTab: 'scanner',
    backendEndpoint: 'POST /api/monetization/order',
    status: 'PRODUCTION_READY',
    modeSupport: 'BOTH',
    storage: 'FIRESTORE',
    mode: 'BOTH',
    production: 'READY',
    hasTests: true,
    description: 'Direct DFY emergency fix request with Indian engineer assignment and WhatsApp update delivery.',
  },
  {
    id: 'LG-027',
    name: 'Live Real-Time Global Scan Counters',
    category: 'UTILITY',
    component: 'ScanCounterStats',
    routeOrTab: 'scanner',
    backendEndpoint: 'GET /api/scan-stats, POST /api/scan-stats/increment-fix',
    status: 'PRODUCTION_READY',
    modeSupport: 'BOTH',
    storage: 'FIRESTORE',
    mode: 'BOTH',
    production: 'READY',
    hasTests: true,
    description: 'Real-time counters tracking total scanned websites, problems diagnosed, and revenue funnels patched in Firestore.',
  },
  {
    id: 'LG-028',
    name: 'Founder Direct Contact & Support Modal',
    category: 'UTILITY',
    component: 'ContactUsModal',
    routeOrTab: 'modal',
    backendEndpoint: 'N/A',
    status: 'PRODUCTION_READY',
    modeSupport: 'BOTH',
    storage: 'FIRESTORE',
    mode: 'BOTH',
    production: 'READY',
    hasTests: true,
    description: 'Direct contact modal with Founder phone (+91 83070 70605) and email (mohitsikarwar123@gmail.com).',
  },
];
